[package]
name = "gtk_fe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.8.0"
tokio.workspace = true
launcher_core.workspace = true
async-channel.workspace = true
reqwest.workspace = true